# Generated by Django 3.2.2 on 2021-05-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_Number_Of_Passengers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Booking_Number_Of_Luggage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Booking_Special_Condition', models.CharField(max_length=255)),
                ('Booking_Total_Seats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Booking_Total_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Booking_Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Destination_Name', models.CharField(max_length=255)),
                ('Destination_City', models.CharField(max_length=255)),
                ('Destination_District', models.CharField(max_length=255)),
                ('Destination_Address', models.TextField()),
                ('Departure_City', models.CharField(max_length=255)),
                ('Departure_Address', models.CharField(max_length=255)),
                ('Destination_Mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destination_Price_Per_KiloMeter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destination_Final_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Station_Name', models.CharField(max_length=255)),
                ('Station_Address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('plateNumber', models.CharField(max_length=255, unique=True)),
                ('gasolineType', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometerRecord', models.CharField(max_length=255)),
                ('currentMaintenanceIssue', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Method', models.CharField(choices=[('Personal Account', 'Personal Account'), ('Bank Transfer', 'Bank Transfer')], default=None, max_length=255, null=True)),
                ('Payment_Receipt_Picture', models.ImageField(blank=True, upload_to='receipt_pics/')),
                ('Payment_Confirmation_Status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Fully Paid', 'Fully Paid')], default=None, max_length=255)),
                ('Cancellation_Confirmation_Status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not Cancel', 'Not Cancel')], default='Not Cancel', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Booking_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookings')),
                ('Financier', models.ForeignKey(limit_choices_to={'groups__name': 'finance'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='DriverScheduleAvailabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Departure_Date_Time', models.DateTimeField()),
                ('tripHoursDuration', models.IntegerField()),
                ('Return_Date_Time', models.DateTimeField(blank=True)),
                ('Number_of_Seat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Remaining_Seat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Driver_Staff_ID', models.ForeignKey(limit_choices_to={'groups__name': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vehicle_Plate_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicles')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destinations')),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='Station_Location_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.stationlocation'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Available_Trips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.driverscheduleavailabilities'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='bookings',
            order_with_respect_to='Customer',
        ),
    ]
