# Generated by Django 3.2.2 on 2021-05-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='Payment_Confirmation_Status',
            new_name='paymentConfirmationStatus',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='Payment_Method',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='Payment_Receipt_Picture',
            new_name='paymentReceiptPicture',
        ),
    ]
