# Generated by Django 3.2.2 on 2021-05-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210510_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='Booking_ID',
            new_name='booking_id',
        ),
    ]
