# Generated by Django 3.2.2 on 2021-05-11 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_rename_booking_id_payments_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverscheduleavailabilities',
            name='Driver_Staff_ID',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Driver Department'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Financier',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Finance Department'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
