# Generated by Django 3.2.2 on 2021-05-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210511_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plateNumber',
            field=models.CharField(max_length=255),
        ),
    ]
