# Generated by Django 3.2.2 on 2021-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210511_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='Destination_Mileage',
            new_name='Destination_Distance',
        ),
    ]
