# Generated by Django 3.2.2 on 2021-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_destination_mileage_destinations_destination_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverscheduleavailabilities',
            name='Schedule_Status',
            field=models.BooleanField(default=False),
        ),
    ]
