# Generated by Django 3.2.2 on 2021-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_driverscheduleavailabilities_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverscheduleavailabilities',
            name='Schedule_Status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
