# Generated by Django 3.2.2 on 2021-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_driverscheduleavailabilities_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverscheduleavailabilities',
            name='Active_Status',
            field=models.BooleanField(default=True),
        ),
    ]
