# Generated by Django 3.2.2 on 2021-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_driverscheduleavailabilities_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Booking_Special_Condition',
            field=models.TextField(max_length=255),
        ),
    ]
