# Generated by Django 3.2.2 on 2021-05-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_bookings_booking_special_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='Departure_Address',
            field=models.TextField(),
        ),
    ]
